### PR TITLE
Use ruby/setup-ruby to simplify CI

### PR DESCRIPTION
**Pull request by eregon**
* [ruby/setup-ruby](https://github.com/ruby/setup-ruby) supports more versions than actions/setup-ruby.
* [ruby/setup-ruby](https://github.com/ruby/setup-ruby) is faster to install Rubies than RVM (and much easier in GitHub Actions).

cc @hsbt @ioquatix

### CODE REVIEW

**Comment by eregon** [comment]
This currently drops `jruby-head`, do we want to keep it? I can try to support it in https://github.com/ruby/setup-ruby.

**Comment by eregon** [comment]
ruby/setup-ruby also allows testing basically any version on any platform.
Should we test `2.3, 2.2, jruby, truffleruby, ruby-head` on macOS and Windows too?

**Comment by hsbt** [comment]
Thanks! I definitely prefer this.

**Comment by ioquatix** [comment]
Nice work!

**Pull request merged**
