### PR TITLE
Removes duplicated inclusion of Rake::DSL

### PR DESCRIPTION
**Pull request by grzuy**
`Rake::DSL` is already included in `Rake::TestCase`

### CODE REVIEW

**Comment by grzuy** [comment]
Apprently test build failed only for ruby 2.1, because `bundle install` command was installing rdoc 5.x previously for all builds, but installed rdoc 6.x for the first time with this PR (despite rdoc 6.x released 1 2 months ago), which is no longer compatible with ruby 2.1

**Comment by grzuy** [comment]
Reported issue here https://github.com/ruby/rake/issues/255

**Comment by hsbt** [comment]
@gazay Can you rebase from master?

**Comment by grzuy** [comment]
@hsbt Rebased

**Comment by yuki24** [comment]
I'm merging this PR since this seems like a safe change. Thanks @grzuy!

**Comment by grzuy** [comment]
Thank you!

**Pull request merged**
