### PR TITLE
Remove old release notes as the maintenance policy has changed.

### PR DESCRIPTION
**Pull request by satoryu**
Old documents sometimes make developers and users confusing like #123 . If the maintainer made a decision they will never provide release notes under `doc/release_notes` and provide `History.rdoc` instead, the old release notes should be removed. 

**CC:** @hsbt @AknEp

### CODE REVIEW

**Comment by drbrain** [comment]
We can't remove old release notes because it makes it harder to find when a bug was introduced.

Merging old-style release notes into History.rdoc would be OK.

**Comment by zzak** [comment]
As an alternative, we could put a README in this directory which explains the current policy for release notes.

**Comment by hsbt** [comment]
I want to merge doc/release_notes and History.rdoc. After that I will merge this pull request.

**Comment by satoryu** [comment]
Thank you for your replies. 

@drbrain @hsbt ok, give me time to merge the old release notes into History.rdoc. 

@zzak good idea it would work! btw, I don't know the current policy the maintainers made. Can I hand over it to the maintainers?

**Comment by satoryu** [comment]
omg, [failed](https://travis-ci.org/ruby/rake/jobs/118927028#L199-L203)...

**Comment by hsbt** [comment]
I invoke failing test again. It works.

**Comment by satoryu** [comment]
Please have a look through the PR again when you have time. @zzak @drbrain

**Comment by hsbt** [comment]
@satoryu Thank you for your work!

**Pull request merged**
