### PR TITLE
Add RuboCop job to Actions

### PR DESCRIPTION
**Pull request by tnir**
Just to avoid drifts such as ones fixed in #423.

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### CODE REVIEW

**Comment by tnir** [comment]
Looks fine to me as far as I see https://github.com/ruby/rake/runs/6703247369?check_suite_focus=true. @hsbt What do you think?

**Comment by hsbt** [comment]
I don't like to add lint to CI mandatory.

It's good to auto-fix each commits in the pull-requests. But I'm not sure how to enable it on the GHA.

**Comment by tnir** [comment]
> I don't like to add lint to CI mandatory.

Just added `continue-on-error: true` to the job not to mandate it.

> It's good to auto-fix each commits in the pull-requests. But I'm not sure how to enable it on the GHA.

Sounds good but RuboCop auto corrections for all cops are not always available.

**Review by hsbt — APPROVED** [review]

**Comment by hsbt** [comment]
Thanks!

**Pull request merged**
